<?php

/**
 * BaseBlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $title
 * @property string $body
 * @property BlogCategory $BlogCategory
 * 
 * @method integer      getCategoryId()   Returns the current record's "category_id" value
 * @method string       getTitle()        Returns the current record's "title" value
 * @method string       getBody()         Returns the current record's "body" value
 * @method BlogCategory getBlogCategory() Returns the current record's "BlogCategory" value
 * @method BlogPost     setCategoryId()   Sets the current record's "category_id" value
 * @method BlogPost     setTitle()        Sets the current record's "title" value
 * @method BlogPost     setBody()         Sets the current record's "body" value
 * @method BlogPost     setBlogCategory() Sets the current record's "BlogCategory" value
 * 
 * @package    cartefinancement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_post');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}