<?php

/**
 * BlogCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogCategory');
    }
}