<?php

/**
 * BlogPostTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPost');
    }

    public function retrieveJob(Doctrine_Query $q)
    {
        return $this->addPostsQuery($q)->fetchOne();
    }


    public function getPosts(Doctrine_Query $q = null)
    {
        return $this->addPostsQuery($q)->execute();
    }

    public function countPosts(Doctrine_Query $q = null)
    {
        return $this->addPostsQuery($q)->count();
    }

    public function addPostsQuery(Doctrine_Query $q = null)
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('BlogPost p');
        }

        $alias = $q->getRootAlias();
        $q->addOrderBy($alias .'.created_at DESC');

        return $q;
    }
}