<?php

/**
 * BlogPost
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cartefinancement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlogPost extends BaseBlogPost
{
    public function __toString()
    {
        return sprintf('%s at %s (%s)', $this->getTitle(), $this->getBody());
    }

    public function getTitleSlug()
    {
        return Blog::slugify($this->getTitle());
    }

    /*public function save(Doctrine_Connection $conn = null)
    {
        // [logic...]

        // $this->isNew() can be used to know if the object has been already created or not.

        // if i'm looking to override the default class behavior, like set a special value in field
        //return parent::save($conn);
    }*/

}
