# You can find more information about this file on the symfony website:
post:
  class: sfDoctrineRouteCollection
  options: { model: BlogPost }

post_show_title:
  url: /post/:title_slug/:id
  class: sfDoctrineRoute
  options: { model: BlogPost, type: object}
  param: { module: post, action: show }
  requirements :
    id: \d+
    sf_method: [get]

#default rules
homepage:
  url:   /
  param: { module: post, action: index}


default_index:
  url:  /:module
  param: { action: index }

default:
  url:  /:module/:action/*
